# multi-stage build custom image to hide the scenario setup
image: leskis/sadpod-dns-base:latest

tasks:
  - name: start the exercise
    # get rid of the obvious evidence
    command: echo "start the activity!"
